version: '3.8'

services:
  app-dev:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
      - playwright-cache:/ms-playwright
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - API_TOKEN=dev_token_123
      - WEBHOOK_TOKEN=dev_webhook_token_456
      - BROWSER_POOL_MIN=1
      - BROWSER_POOL_MAX=3
      - BROWSER_MAX_USES=50
    ports:
      - "3000:3000"
    command: yarn dev
    depends_on:
      - redis
    networks:
      - pdf-network

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"
    networks:
      - pdf-network

volumes:
  playwright-cache:

networks:
  pdf-network:
    driver: bridge
